"""empty message

Revision ID: 00c7b36a72a2
Revises: 
Create Date: 2022-08-22 16:33:45.005138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00c7b36a72a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gen', sa.String(length=120), nullable=False),
    sa.Column('genTwo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.Column('traits_and_interests', sa.String(length=250), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p1_id', sa.Integer(), nullable=True),
    sa.Column('p2_id', sa.Integer(), nullable=True),
    sa.Column('p1_accept', sa.Boolean(), nullable=True),
    sa.Column('p2_accept', sa.Boolean(), nullable=True),
    sa.Column('p2_decline', sa.Boolean(), nullable=True),
    sa.Column('p1_rating', sa.Integer(), nullable=True),
    sa.Column('p2_rating', sa.Integer(), nullable=True),
    sa.Column('p1_text_reviews', sa.Text(), nullable=True),
    sa.Column('p2_text_reviews', sa.Text(), nullable=True),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['p1_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['p2_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date')
    op.drop_table('profile')
    op.drop_table('gender')
    op.drop_table('gen')
    # ### end Alembic commands ###
