"""empty message

Revision ID: 1549eaf49a44
Revises: 396ae21da132
Create Date: 2022-08-13 00:19:39.306068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1549eaf49a44'
down_revision = '396ae21da132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('p2_answer', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('date', 'p2_answer')
    # ### end Alembic commands ###
