"""empty message

Revision ID: 396ae21da132
Revises: 68ae5cef293c
Create Date: 2022-08-10 21:58:06.469544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396ae21da132'
down_revision = '68ae5cef293c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('profile', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('profile', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
