"""empty message

Revision ID: 634affcbd9f3
Revises: 
Create Date: 2022-08-07 16:23:27.588475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634affcbd9f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.String(length=250), nullable=False),
    sa.Column('traits_and_interests', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('gender')
    # ### end Alembic commands ###
