"""empty message

Revision ID: 68ae5cef293c
Revises: f2639af22254
Create Date: 2022-08-09 00:09:19.039496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ae5cef293c'
down_revision = 'f2639af22254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('profile', 'first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('profile', 'last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('profile', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('profile', 'image_url',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('profile', 'bio',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('profile', 'traits_and_interests',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'traits_and_interests',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('profile', 'bio',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('profile', 'image_url',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('profile', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('profile', 'last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('profile', 'first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('profile', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
