"""empty message

Revision ID: 6abc769b89d7
Revises: 9c508aa25440
Create Date: 2022-07-30 00:31:11.217566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abc769b89d7'
down_revision = '9c508aa25440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_bio_key', 'profile', type_='unique')
    op.drop_constraint('profile_image_url_key', 'profile', type_='unique')
    op.drop_constraint('profile_name_key', 'profile', type_='unique')
    op.drop_constraint('profile_traits_and_interests_key', 'profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('profile_traits_and_interests_key', 'profile', ['traits_and_interests'])
    op.create_unique_constraint('profile_name_key', 'profile', ['name'])
    op.create_unique_constraint('profile_image_url_key', 'profile', ['image_url'])
    op.create_unique_constraint('profile_bio_key', 'profile', ['bio'])
    # ### end Alembic commands ###
