"""empty message

Revision ID: 83ccb83bcfb0
Revises: 99f96c50fb7e
Create Date: 2022-08-06 00:26:56.768433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ccb83bcfb0'
down_revision = '99f96c50fb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_gender_fkey', 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'gender', ['gender'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key('profile_gender_fkey', 'profile', 'gender', ['gender'], ['id'])
    # ### end Alembic commands ###
