"""empty message

Revision ID: 99f96c50fb7e
Revises: 6abc769b89d7
Create Date: 2022-08-06 00:19:23.132171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f96c50fb7e'
down_revision = '6abc769b89d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('user')
    op.add_column('profile', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('profile', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('profile', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.add_column('profile', sa.Column('password', sa.String(length=80), nullable=False))
    op.add_column('profile', sa.Column('gender', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'profile', ['email'])
    op.create_foreign_key(None, 'profile', 'gender', ['gender'], ['id'])
    op.drop_column('profile', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_column('profile', 'gender')
    op.drop_column('profile', 'password')
    op.drop_column('profile', 'last_name')
    op.drop_column('profile', 'first_name')
    op.drop_column('profile', 'email')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('gender')
    # ### end Alembic commands ###
