"""empty message

Revision ID: ac34ce3a65f3
Revises: d72a8c373c6b
Create Date: 2022-08-15 22:39:47.518380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac34ce3a65f3'
down_revision = 'd72a8c373c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('p1_accept', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('date', 'p1_accept')
    # ### end Alembic commands ###
