"""empty message

Revision ID: b51af91725a6
Revises: d36789fc62e5
Create Date: 2022-08-23 23:23:12.439989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51af91725a6'
down_revision = 'd36789fc62e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('profile', sa.Column('country', sa.String(length=80), nullable=True))
    op.add_column('profile', sa.Column('zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'zip_code')
    op.drop_column('profile', 'country')
    op.drop_column('profile', 'city')
    # ### end Alembic commands ###
