"""empty message

Revision ID: d36789fc62e5
Revises: ac34ce3a65f3
Create Date: 2022-08-17 22:25:03.481896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36789fc62e5'
down_revision = 'ac34ce3a65f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('p2_decline', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('date', 'p2_decline')
    # ### end Alembic commands ###
