"""empty message

Revision ID: d72a8c373c6b
Revises: 2de9603e2847
Create Date: 2022-08-13 19:32:05.061743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72a8c373c6b'
down_revision = '2de9603e2847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('p2_accept', sa.Boolean(), nullable=True))
    op.drop_column('date', 'p2_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('p2_answer', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('date', 'p2_accept')
    # ### end Alembic commands ###
