"""empty message

Revision ID: f2639af22254
Revises: 634affcbd9f3
Create Date: 2022-08-08 23:25:32.591891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2639af22254'
down_revision = '634affcbd9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p1_id', sa.Integer(), nullable=True),
    sa.Column('p2_id', sa.Integer(), nullable=True),
    sa.Column('p1_rating', sa.Integer(), nullable=True),
    sa.Column('p2_rating', sa.Integer(), nullable=True),
    sa.Column('p1_text_reviews', sa.Text(), nullable=True),
    sa.Column('p2_text_reviews', sa.Text(), nullable=True),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['p1_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['p2_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date')
    # ### end Alembic commands ###
